repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: debug-statements
    -   id: requirements-txt-fixer

-   repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.8.0
    hooks:
    -   id: ruff
        types_or: [ python, pyi ]
        args: [ --fix ]
    -   id: ruff-format
        types_or: [ python, pyi ]

-   repo: https://github.com/commitizen-tools/commitizen
    rev: v4.0.0
    hooks:
    -   id: commitizen
    -   id: commitizen-branch
        stages: [pre-push]
