#!/usr/bin/env python3
"""Mypy ratchet gate for CI (Q5, 2026-08 code-quality review).

The codebase predates type checking, so a hard mypy gate would block on
~90 pre-existing errors. Instead we ratchet: the set of current mypy errors
must be a *subset* of the baseline set recorded in ``.mypy-baseline``. New
errors fail CI; fixed errors are fine. When the baseline shrinks, regenerate
it (``uv run mypy --baseline`` style — see below) so the gate stays tight.

Baseline format: one normalized error line per line, sorted. A normalized
line drops the leading ``path:`` (only the filename + line + code + message
survive) so a file rename or a re-baseline after a bulk move doesn't read as
100% new errors. The column number is dropped too (whitespace edits would
otherwise churn every line).

Usage:
    python scripts/check_mypy_baseline.py
        # CI gate: exit 0 if no new errors
    python scripts/check_mypy_baseline.py --update
        # rewrite the baseline from current output

The gate exits:
    0 — no new errors (current ⊆ baseline)
    1 — new errors present (printed), OR mypy itself failed to run
"""

from __future__ import annotations

import re
import subprocess
import sys
from pathlib import Path

BASELINE_FILE = Path(__file__).resolve().parent.parent / ".mypy-baseline"

# A mypy line looks like: path/to/file.py:LINE: error: Message  [code]
# (the column may appear in some output modes; make it optional).
_ERROR_RE = re.compile(
    r"^(?P<loc>[^:]+\.py):(?P<line>\d+):(?:(?P<col>\d+):)? error: (?P<msg>.+)$"
)


def _run_mypy() -> str:
    """Run mypy via uv; return its stdout (the error list)."""
    proc = subprocess.run(
        ["uv", "run", "mypy"],
        capture_output=True,
        text=True,
    )
    # mypy exits non-zero when it finds errors; that's expected, not a gate
    # failure. Only a broken invocation (non-1/2 exit + no stdout) is fatal.
    if proc.returncode not in (0, 1) or not proc.stdout and proc.returncode != 0:
        sys.stderr.write(
            f"mypy failed to run (exit {proc.returncode}):\n{proc.stderr}\n"
        )
        return None  # type: ignore[return-value]
    return proc.stdout


def _normalize(stdout: str) -> set[str]:
    """Normalize mypy error lines into a stable set.

    Drop the directory path (keep basename + line), the column, and sort, so a
    file move or a whitespace-only diff doesn't churn the whole set.
    """
    lines: set[str] = set()
    for raw in stdout.splitlines():
        m = _ERROR_RE.match(raw)
        if not m:
            continue
        path = Path(m["loc"]).name
        lines.add(f"{path}:{m['line']}: {m['msg'].strip()}")
    return lines


def _read_baseline() -> set[str]:
    if not BASELINE_FILE.exists():
        return set()
    return {
        line.strip()
        for line in BASELINE_FILE.read_text().splitlines()
        if line.strip() and not line.startswith("#")
    }


def _write_baseline(errors: set[str]) -> None:
    header = (
        "# Mypy error baseline — regenerated by check_mypy_baseline.py --update.\n"
        "# CI fails when mypy emits a line NOT in this file. Fix errors and re-run\n"
        "# --update to lower the count; never add lines without a documented reason.\n"
    )
    BASELINE_FILE.write_text(header + "\n".join(sorted(errors)) + "\n")


def main() -> int:
    update = "--update" in sys.argv
    stdout = _run_mypy()
    if stdout is None:
        return 1
    current = _normalize(stdout)

    if update:
        _write_baseline(current)
        print(f"baseline rewritten: {len(current)} errors")
        return 0

    baseline = _read_baseline()
    new_errors = sorted(current - baseline)
    fixed_errors = sorted(baseline - current)

    if new_errors:
        print(f"mypy ratchet FAILED: {len(new_errors)} new error(s) not in baseline:")
        for e in new_errors:
            print(f"  + {e}")
        print()
        print("Fix the new errors, or if they are pre-existing and legitimate,")
        print("regenerate the baseline: python scripts/check_mypy_baseline.py --update")
        return 1

    if fixed_errors:
        print(
            f"mypy ratchet PASSED: 0 new, {len(fixed_errors)} fixed. "
            f"Baseline is now stale ({len(current)}/{len(baseline)}). "
            f"Regenerate: python scripts/check_mypy_baseline.py --update"
        )
    else:
        print(f"mypy ratchet PASSED: 0 new, 0 fixed ({len(current)} baseline errors).")
    return 0


if __name__ == "__main__":
    sys.exit(main())
